services:
  api:
    container_name: urlshort-api
    build:
      context: .
      dockerfile: ./backend/docker/prod/Dockerfile
    restart: always
    environment:
      URLSHORT_BASE_URL: urlshort-api
      URLSHORT_DATABASE: postgres
      URLSHORT_ENVIRONMENT: production
      URLSHORT_FRONTEND_URL: urlshort-frontend
      PGHOST: 192.168.123.142
      PGUSER: urlshort
      PGPORT: 5432
      PGPASSWORD: urlshort
      PGDATABASE: urlshortener
    expose:
      - "8000"
    networks:
      - urlshort-network

  frontend:
    container_name: urlshort-frontend
    build:
      context: .
      dockerfile: ./frontend/docker/prod/Dockerfile
    env_file:
      - ./frontend/.env
    restart: always
    expose:
      - "80"
    networks:
      - urlshort-network

  nginx:
    container_name: urlshort-nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
    networks:
      - urlshort-network

networks:
  urlshort-network:
    driver: bridge