services:
  api:
    container_name: urlshort-api
    build:
      context: .
      dockerfile: ./backend/docker/prod/Dockerfile
    restart: always
    environment:
      URLSHORT_BASE_URL: urlshort-api
      URLSHORT_DATABASE: postgres
      URLSHORT_ENVIRONMENT: production
      URLSHORT_FRONTEND_URL: urlshort-frontend
      PGHOST: db
      PGUSER: urlshort
      PGPORT: 5432
      PGPASSWORD: urlshort
      PGDATABASE: urlshort
    expose:
      - "8000"

  frontend:
    container_name: urlshort-frontend
    build:
      context: .
      dockerfile: ./frontend/docker/prod/Dockerfile
    env_file:
      - ./frontend/.env
    restart: always
    expose:
      - "80"

  db:
    container_name: urlshort-db
    image: postgres:15
    environment:
      POSTGRES_USER: urlshort
      POSTGRES_PASSWORD: urlshort
      POSTGRES_DB: urlshort
    ports:
      - "5431:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshort"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    container_name: urlshort-nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend